### ISSUE TITLE
Can you please add a button for currently available room/ lab for exam preparation 

### ISSUE THREAD

**Issue by ranehal** [nur-zaman/isTheClassroomEmpty#3]
Most of the lab is always busy and it is hard to input all the lab room codes, thanks in advance

**Comment by nur-zaman** [comment]
Hello,
You can view all the available empty rooms from here [https://nur-zaman.github.io/isTheClassroomEmpty/fullList.html](https://nur-zaman.github.io/isTheClassroomEmpty/fullList.html) , instead of entering each one manually.

I don't have a a list of lab rooms separately, but if you can provide one then I can add the filter for lab rooms.
